export const aboutmeItems = [
  {
    tab: 1,
    url: "whoiam.com",
    heading: "I Am",
    title: "Wer bin ich?",
    text: "Ich schreibe Code, trinke Tee und behebe Bugs manchmal sogar in dieser Reihenfolge. Seit 2022 entwickle ich Webanwendungen mit HTML, CSS und Javascript und ich liebe es, digitale Lösungen zu gestalten.",
    icon: "../assets/img/hallo.png",
    picture: "../../assets/img/hallo.png",
  },
  {
    tab: 2,
    url: "whatido.com",
    heading: "To Do",
    title: "Was mache ich?",
    text: "Mein Tech-Stack umfasst Vue.js und TailwindCSS für ein schlankes, performantes Frontend. Im Backend arbeite ich mit Node.js für skalierbare Web-apps, PHP für klassische Webentwicklung und C# für enterprise-Anwendungen. Mit MariaDB und SQL erstelle ich robuste relationale Datenbanken, optimiere Queries und Implementiere sichere Datenstrukturen.",
    icon: "../assets/img/work-life-balance.png",
    picture: "../assets/img/aboutMe-picture.jpg",
  },
  {
    tab: 3,
    url: "whereilearned.com",
    heading: "I Learned @",
    title: "Meine Schullaufbahn?",
    text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vitae quam ab iste sunt dolore, id velit repudiandae aperiam iusto labore doloribus error eaque temporibus nihil consequatur unde. Obcaecati, rerum quo.",
    icon: "../assets/img/werdegang.png",
    picture: "../assets/img/aboutMe-picture.jpg",
  },
  {
    tab: 4,
    url: "whoiwork.com",
    heading: "I Work For",
    title: "Mein Beruflicher Werdegang?",
    text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vitae quam ab iste sunt dolore, id velit repudiandae aperiam iusto labore doloribus error eaque temporibus nihil consequatur unde. Obcaecati, rerum quo.",
    icon: "../assets/img/zukunft.png",
    picture: "../assets/img/aboutMe-picture.jpg",
  },
  {
    tab: 5,
    url: "whereiwill.com",
    heading: "I Will Be",
    title: "Wo sehe ich mich in Zukunft?",
    text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vitae quam ab iste sunt dolore, id velit repudiandae aperiam iusto labore doloribus error eaque temporibus nihil consequatur unde. Obcaecati, rerum quo.",
    icon: "../assets/img/hallo.png",
    picture: "../assets/img/aboutMe-picture.jpg",
  },
];
