export const skillsItemsCards = [
  {
    text: "git",
    textWidth: "lg:text-2xl xl:text-3xl",
    icon: "fa-brands fa-git-alt",
    starCount: 9,
    atk: 200,
    def: 400,
    ability: "Verwalte Versionen und Quellcode.",
    description:
      "Git ist ein verteiltes Versionskontrollsystem, das Entwicklern hilft, Code zu verwalten und zusammenzuarbeiten.",
    cardType: "Tool",
  },
  {
    text: "GitHub",
    textWidth: "text-xl",
    icon: "fa-brands fa-github",
    starCount: 9,
    atk: 400,
    def: 400,
    ability: "Hosting für Git-Repositories.",
    description:
      "GitHub ist eine Plattform, die Entwicklern hilft, Code zu hosten, zu teilen und mit anderen zu kollaborieren.",
    cardType: "Plattform",
  },
  {
    text: "BitBucket",
    textWidth: "text-xl",
    icon: "fa-brands fa-bitbucket",
    starCount: 8,
    atk: 800,
    def: 800,
    ability: "Git und Mercurial Repositories für Teams.",
    description:
      "Bitbucket bietet Git- und Mercurial-Repository-Hosting sowie eine Plattform für Codezusammenarbeit.",
    cardType: "Plattform",
  },
  {
    text: "GitLab",
    textWidth: "text-xl",
    icon: "fa-brands fa-gitlab",
    starCount: 3,
    atk: 800,
    def: 800,
    ability: "DevOps- und CI/CD-Tools.",
    description:
      "GitLab ist eine vollständige DevOps-Plattform, die Git-Repositories, CI/CD und DevOps-Management umfasst.",
    cardType: "Plattform",
  },
  {
    text: "Windows",
    textWidth: "text-xl",
    icon: "fa-brands fa-windows",
    starCount: 10,
    atk: 500,
    def: 100,
    ability: "Windows-Betriebssystem.",
    description:
      "Microsoft Windows ist ein weit verbreitetes Betriebssystem für Computer, das eine benutzerfreundliche Oberfläche bietet.",
    cardType: "Betriebssystem",
  },
  {
    text: "Linux",
    textWidth: "text-xl",
    icon: "fa-brands fa-linux",
    starCount: 7,
    atk: 1000,
    def: 1500,
    ability: "Offenes Betriebssystem.",
    description:
      "Linux ist ein Open-Source-Betriebssystem, das für seine Stabilität, Sicherheit und Anpassbarkeit bekannt ist.",
    cardType: "Betriebssystem",
  },
  {
    text: "Docker",
    textWidth: "text-xl",
    icon: "fa-brands fa-docker",
    starCount: 3,
    atk: 600,
    def: 500,
    ability: "Containerisierung von Anwendungen.",
    description:
      "Docker ermöglicht es Entwicklern, Anwendungen in isolierten Containern zu erstellen und auszuführen.",
    cardType: "Tool",
  },
  {
    text: "CSS",
    textWidth: "text-xl",
    icon: "fa-brands fa-css3",
    starCount: 10,
    atk: 250,
    def: 500,
    ability: "Gestaltung von Webseiten.",
    description:
      "CSS (Cascading Style Sheets) wird verwendet, um das Design und Layout von Webseiten zu gestalten.",
    cardType: "Sprache",
  },
  {
    text: "JS",
    textWidth: "text-xl",
    icon: "fa-brands fa-js",
    starCount: 10,
    atk: 500,
    def: 100,
    ability: "Interaktive Webseitenfunktionen.",
    description:
      "JavaScript ist eine Programmiersprache, die verwendet wird, um interaktive und dynamische Funktionen auf Webseiten zu erstellen.",
    cardType: "Sprache",
  },
  {
    text: "Vue",
    textWidth: "text-xl",
    icon: "fa-brands fa-vuejs",
    starCount: 10,
    atk: 900,
    def: 600,
    ability: "Fortschrittliches JavaScript-Framework.",
    description:
      "Vue.js ist ein JavaScript-Framework, das Entwicklern hilft, moderne Benutzeroberflächen und SPAs zu erstellen.",
    cardType: "Framework",
  },
  {
    text: "Node",
    textWidth: "text-xl",
    icon: "fa-brands fa-node",
    starCount: 5,
    atk: 700,
    def: 400,
    ability: "Serverseitige JavaScript-Ausführung.",
    description:
      "Node.js ist eine serverseitige JavaScript-Umgebung, die auf der V8 JavaScript Engine basiert.",
    cardType: "Runtime",
  },
  {
    text: "Bootstrap",
    textWidth: "text-xl",
    icon: "fa-brands fa-bootstrap",
    starCount: 10,
    atk: 0,
    def: 10,
    ability: "Responsive Frontend-Framework.",
    description:
      "Bootstrap ist ein Frontend-Framework, das Entwicklern hilft, schnell responsive Webseiten zu erstellen.",
    cardType: "Framework",
  },
  {
    text: "VS Code",
    textWidth: "text-xl",
    icon: "bi bi-window",
    starCount: 10,
    atk: 500,
    def: 500,
    ability: "Code-Editor mit vielen Erweiterungen.",
    description:
      "Visual Studio Code ist ein leistungsstarker und flexibler Code-Editor mit umfangreichen Erweiterungsmöglichkeiten.",
    cardType: "IDE",
  },
  {
    text: "Visual Studio",
    textWidth: "text-xl",
    icon: "bi bi-window-split",
    starCount: 4,
    atk: 1500,
    def: 1000,
    ability: "Entwicklungsumgebung für verschiedene Programmiersprachen.",
    description:
      "Visual Studio ist eine integrierte Entwicklungsumgebung (IDE) für verschiedene Programmiersprachen wie C#, C++, und Python.",
    cardType: "IDE",
  },
];
